esphome:
  name: pump_station
  libraries:
    - "SPI"
    - "Ticker"
    - "SX126x-Arduino"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/PaulSchulz/esphome-lora-sx126x
      ref: main
    components: ["lora_sx126x"]

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  password: !secret ota_password

api:
  encryption:
    key: !secret api_encryption_key

web_server:
  port: 80

lora_sx126x:
  rf_frequency: 915000000
  pin_lora_reset: 12
  pin_lora_dio_1: 14
  pin_lora_busy: 13
  pin_lora_nss: 8
  pin_lora_sclk: 9
  pin_lora_miso: 11
  pin_lora_mosi: 10

sensor:
  - platform: lora_sx126x
    id: lora_rssi
    name: "LoRa RSSI"

binary_sensor:
  - platform: lora_sx126x
    id: pump_cmd
    on_string: "PUMP_ON"
    off_string: "PUMP_OFF"
    on_press:
      - switch.turn_on: pump_relay
    on_release:
      - switch.turn_off: pump_relay

switch:
  - platform: gpio
    id: pump_relay
    name: "Pump Relay"
    pin: GPIO5
